<section class="hero is-medium is-bold">
    <nav class="panel">
        <a href="<?=$adminRoot;?>home" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Ana Sayfa</a>
        <p class="panel-heading">Kategori Ayarları</p>
        <a href="<?=$adminRoot;?>category/all" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Tüm Kategoriler</a>
        <a href="<?=$adminRoot;?>category/new" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Yeni Kategori</a>
        <p class="panel-heading">Etiket Ayarları</p>
        <a href="<?=$adminRoot;?>tag/all" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Tüm Etiketler</a>
        <a href="<?=$adminRoot;?>tag/new" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Yeni Etiket</a>
        <p class="panel-heading">Paylaşım Ayarları</p>
        <a href="<?=$adminRoot;?>post/all" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Tüm Paylaşımlar</a>
        <a href="<?=$adminRoot;?>post/new" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Yeni Paylaşım</a>
        <p class="panel-heading">Genel Ayarlar</p>
        <a href="<?=$adminRoot;?>settings" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Site Ayarları</a>
        <a href="<?=$adminRoot;?>adminSettings" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Şifre Değiştir</a>
        <a href="<?=$adminRoot;?>logout" class="panel-block"><span class="panel-icon"><i class="fa fa-book"></i></span> Çıkış Yap</a>
    </nav>
</section>