<div class="field">
    <label class="label">Ad</label>
    <p class="control">
        <input class="input" type="text" id="name" placeholder="Maksimum 45 karakter">
    </p>
</div>
<div class="field" style="margin-top: 3rem;">
    <p class="control" style="margin-top: 15px;"><button id="new" class="button is-primary is-outlined is-fullwidth">Oluştur</button></p>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        var newButton = $("#new");
        var nameInput    = $("#name");

        var beforeSend = function () {
            newButton.addClass("is-loading");
            newButton.blur();
            nameInput.addClass("is-disabled");
        };

        var complete = function () {
            newButton.removeClass("is-loading");
            nameInput.removeClass("is-disabled");
        };

        var error = function () {
            alert("Başarısız istek sayfayı yenileyin.");
        };

        var success = function (data) {
            alert(data._);
            if (data.success) {
                window.location = "all";
            }
        };

        newButton.click(function () {
            $.ajax({
                method: "POST",
                data: {
                    tag: nameInput.val()
                },
                cache: false,
                beforeSend: beforeSend,
                success: success,
                error: error,
                complete: complete
            });
        });
    });
</script>