<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title><?=trim($site["name"]);?> | <?=$title;?></title>

<link rel="canonical" href="<?=(isset($_SERVER['HTTPS']) ? "https" : "http")."://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];?>" />
<!--
<link rel="shortcut icon" type="image/x-icon" href="<?=$root."public/favicon.ico";?>">
<link rel="icon" type="image/png" href="<?=$root."public/favicon-32x32.png";?>" sizes="32x32" />
<link rel="icon" type="image/png" href="<?=$root."public/favicon-16x16.png";?>" sizes="16x16" />
-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/css/froala_style.min.css' rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="<?=$root."public/css/style.css";?>">
