<!doctype html>
<html lang="tr">
<head>
    <?php require $Elements("head"); ?>
</head>
<body>
    <?php require $Elements("header"); ?>
    <section class="hero">
        <div class="columns is-multiline is-mobile">
            <div class="column is-one-third"><?php require $Elements("panel");?></div>
            <div class="column" style="margin-top: 15px;"><?php require $Elements($Element); ?></div>
        </div>
    </section>
</body>
</html>